### ISSUE TITLE
Static web generator (scheduled job): Skipping generating a page for a page that has a language branch in status draft  

### ISSUE THREAD

**Issue by maer0216-star** [7h3Rabbit/StaticWebEpiserverPlugin#71]
Hi!

Possible bug?

When the Static web generator (scheduled job) is running it seems to skip generating a page if a language branch exist and is in status draft. For example if a page is published  in swedish and has a draft english language branch. Then it seems like the job is skipping generating the swedish page (and english since its in draft status). Expected behaviour: The swedish page is generated but not the english.

Thanks
Magnus

**Comment by 7h3Rabbit** [comment]
@maer0216-star  it should now be solved. Please verify and let me know :)

**Comment by maer0216-star** [comment]
@7h3Rabbit Thanks, but it does not solve the issue. I wonder if the ignorePage must be reset for each loop over lang? Since maybe the draft lang is first and then the ignorePage == true for the second lang as well (which maybe be published )

**Comment by 7h3Rabbit** [comment]
@maer0216-star good catch. please verify now :)

**Comment by maer0216-star** [comment]
@7h3Rabbit  Great, now it works :) Thanks!
